// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authsqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (openid, nickname, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type CreateUserParams struct {
	Openid    string  `json:"openid"`
	Nickname  string  `json:"nickname"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Openid, arg.Nickname, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOpenID = `-- name: GetUserByOpenID :one
SELECT id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
FROM users
WHERE openid = $1
`

func (q *Queries) GetUserByOpenID(ctx context.Context, openid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOpenID, openid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAppProfile = `-- name: UpdateUserAppProfile :one
UPDATE users
SET nickname = $2,
    real_name = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type UpdateUserAppProfileParams struct {
	ID       int64   `json:"id"`
	Nickname string  `json:"nickname"`
	RealName *string `json:"real_name"`
}

func (q *Queries) UpdateUserAppProfile(ctx context.Context, arg UpdateUserAppProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAppProfile, arg.ID, arg.Nickname, arg.RealName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
