// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAppleNotification struct {
	ID          string             `json:"id"`
	Subject     string             `json:"subject"`
	EventType   string             `json:"event_type"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	EventTime   int64              `json:"event_time"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type AuthChallenge struct {
	ID        string             `json:"id"`
	NonceHash string             `json:"nonce_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type AuthCode struct {
	Key       string             `json:"key"`
	Hash      string             `json:"hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int32              `json:"attempts"`
	Active    bool               `json:"active"`
}

type AuthIdentity struct {
	UserID               int64              `json:"user_id"`
	Provider             string             `json:"provider"`
	Subject              string             `json:"subject"`
	PasswordHash         string             `json:"password_hash"`
	AppleRefresh         []byte             `json:"apple_refresh"`
	AppleAuthenticatedAt pgtype.Timestamptz `json:"apple_authenticated_at"`
}

type AuthQuota struct {
	Key       string             `json:"key"`
	Count     int32              `json:"count"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type AuthRefreshHistory struct {
	RefreshHash string             `json:"refresh_hash"`
	UserID      int64              `json:"user_id"`
	FamilyID    string             `json:"family_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type AuthSession struct {
	ID              string             `json:"id"`
	UserID          int64              `json:"user_id"`
	Provider        string             `json:"provider"`
	FamilyID        string             `json:"family_id"`
	RefreshHash     string             `json:"refresh_hash"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type GoldDailyBar struct {
	Symbol      string             `json:"symbol"`
	TradingDate pgtype.Date        `json:"trading_date"`
	Open        float64            `json:"open"`
	High        float64            `json:"high"`
	Low         float64            `json:"low"`
	Close       float64            `json:"close"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GoldNativeSample struct {
	Instrument string             `json:"instrument"`
	Bucket     pgtype.Timestamptz `json:"bucket"`
	SampledAt  pgtype.Timestamptz `json:"sampled_at"`
	SourceAt   pgtype.Timestamptz `json:"source_at"`
	Price      float64            `json:"price"`
}

type GoldRealtimeSample struct {
	Symbol    string             `json:"symbol"`
	Bucket    pgtype.Timestamptz `json:"bucket"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	SourceAt  pgtype.Timestamptz `json:"source_at"`
	PriceCny  float64            `json:"price_cny"`
}

type User struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
