// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
