-- +goose Up
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid VARCHAR(128) NOT NULL UNIQUE,
    nickname VARCHAR(120) NOT NULL DEFAULT '',
    avatar_url TEXT NULL,
    real_name VARCHAR(120) NULL,
    phone_number VARCHAR(32) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT users_openid_not_blank CHECK (BTRIM(openid) <> ''),
    CONSTRAINT users_status_check CHECK (status IN ('active', 'frozen'))
);

-- +goose Down
DROP TABLE IF EXISTS users;
