// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package marketsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadDaily = `-- name: LoadDaily :many
SELECT trading_date, open, high, low, close FROM gold_daily_bars
WHERE symbol=$1 ORDER BY trading_date
`

type LoadDailyRow struct {
	TradingDate pgtype.Date
	Open        float64
	High        float64
	Low         float64
	Close       float64
}

func (q *Queries) LoadDaily(ctx context.Context, symbol string) ([]LoadDailyRow, error) {
	rows, err := q.db.Query(ctx, loadDaily, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadDailyRow
	for rows.Next() {
		var i LoadDailyRow
		if err := rows.Scan(
			&i.TradingDate,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadNativeSamples = `-- name: LoadNativeSamples :many
SELECT target.sampled_at,target.source_at,target.price FROM gold_native_samples AS target WHERE target.instrument=$1 AND target.sampled_at >=
 (SELECT MAX(latest.source_at)-INTERVAL '20 minutes' FROM gold_native_samples AS latest WHERE latest.instrument=$1) ORDER BY sampled_at
`

type LoadNativeSamplesRow struct {
	SampledAt pgtype.Timestamptz
	SourceAt  pgtype.Timestamptz
	Price     float64
}

func (q *Queries) LoadNativeSamples(ctx context.Context, instrument string) ([]LoadNativeSamplesRow, error) {
	rows, err := q.db.Query(ctx, loadNativeSamples, instrument)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadNativeSamplesRow
	for rows.Next() {
		var i LoadNativeSamplesRow
		if err := rows.Scan(&i.SampledAt, &i.SourceAt, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRealtime = `-- name: LoadRealtime :many
SELECT sampled_at, source_at, price_cny FROM gold_realtime_samples
WHERE symbol='XAUUSD' AND sampled_at >=
 (SELECT MAX(source_at) - INTERVAL '20 minutes' FROM gold_realtime_samples WHERE symbol='XAUUSD') ORDER BY sampled_at
`

type LoadRealtimeRow struct {
	SampledAt pgtype.Timestamptz
	SourceAt  pgtype.Timestamptz
	PriceCny  float64
}

func (q *Queries) LoadRealtime(ctx context.Context) ([]LoadRealtimeRow, error) {
	rows, err := q.db.Query(ctx, loadRealtime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadRealtimeRow
	for rows.Next() {
		var i LoadRealtimeRow
		if err := rows.Scan(&i.SampledAt, &i.SourceAt, &i.PriceCny); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNativeSamples = `-- name: PruneNativeSamples :exec
DELETE FROM gold_native_samples AS target WHERE target.instrument=$1 AND target.sampled_at <
 (SELECT MAX(latest.source_at)-INTERVAL '20 minutes' FROM gold_native_samples AS latest WHERE latest.instrument=$1)
`

func (q *Queries) PruneNativeSamples(ctx context.Context, instrument string) error {
	_, err := q.db.Exec(ctx, pruneNativeSamples, instrument)
	return err
}

const pruneRealtime = `-- name: PruneRealtime :exec
DELETE FROM gold_realtime_samples WHERE symbol='XAUUSD' AND sampled_at <
 (SELECT MAX(source_at) - INTERVAL '20 minutes' FROM gold_realtime_samples WHERE symbol='XAUUSD')
`

func (q *Queries) PruneRealtime(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneRealtime)
	return err
}

const saveDaily = `-- name: SaveDaily :exec
INSERT INTO gold_daily_bars (symbol, trading_date, open, high, low, close)
SELECT $1::text, unnest($2::date[]), unnest($3::float8[]),
 unnest($4::float8[]), unnest($5::float8[]), unnest($6::float8[])
ON CONFLICT (symbol, trading_date) DO UPDATE SET open=EXCLUDED.open, high=EXCLUDED.high,
 low=EXCLUDED.low, close=EXCLUDED.close, updated_at=NOW()
WHERE (gold_daily_bars.open,gold_daily_bars.high,gold_daily_bars.low,gold_daily_bars.close)
 IS DISTINCT FROM (EXCLUDED.open,EXCLUDED.high,EXCLUDED.low,EXCLUDED.close)
`

type SaveDailyParams struct {
	Symbol string
	Dates  []pgtype.Date
	Opens  []float64
	Highs  []float64
	Lows   []float64
	Closes []float64
}

func (q *Queries) SaveDaily(ctx context.Context, arg SaveDailyParams) error {
	_, err := q.db.Exec(ctx, saveDaily,
		arg.Symbol,
		arg.Dates,
		arg.Opens,
		arg.Highs,
		arg.Lows,
		arg.Closes,
	)
	return err
}

const saveNativeSample = `-- name: SaveNativeSample :exec
INSERT INTO gold_native_samples(instrument,bucket,sampled_at,source_at,price)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT(instrument,bucket) DO UPDATE SET sampled_at=EXCLUDED.sampled_at,source_at=EXCLUDED.source_at,price=EXCLUDED.price
WHERE EXCLUDED.sampled_at > gold_native_samples.sampled_at
`

type SaveNativeSampleParams struct {
	Instrument string
	Bucket     pgtype.Timestamptz
	SampledAt  pgtype.Timestamptz
	SourceAt   pgtype.Timestamptz
	Price      float64
}

func (q *Queries) SaveNativeSample(ctx context.Context, arg SaveNativeSampleParams) error {
	_, err := q.db.Exec(ctx, saveNativeSample,
		arg.Instrument,
		arg.Bucket,
		arg.SampledAt,
		arg.SourceAt,
		arg.Price,
	)
	return err
}

const saveRealtime = `-- name: SaveRealtime :exec
INSERT INTO gold_realtime_samples (symbol, bucket, sampled_at, source_at, price_cny)
VALUES ('XAUUSD', $1, $2, $3, $4)
ON CONFLICT (symbol, bucket) DO UPDATE SET sampled_at=EXCLUDED.sampled_at,
 source_at=EXCLUDED.source_at, price_cny=EXCLUDED.price_cny
WHERE EXCLUDED.sampled_at > gold_realtime_samples.sampled_at
`

type SaveRealtimeParams struct {
	Bucket    pgtype.Timestamptz
	SampledAt pgtype.Timestamptz
	SourceAt  pgtype.Timestamptz
	PriceCny  float64
}

func (q *Queries) SaveRealtime(ctx context.Context, arg SaveRealtimeParams) error {
	_, err := q.db.Exec(ctx, saveRealtime,
		arg.Bucket,
		arg.SampledAt,
		arg.SourceAt,
		arg.PriceCny,
	)
	return err
}
