// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package marketsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GoldDailyBar struct {
	Symbol      string
	TradingDate pgtype.Date
	Open        float64
	High        float64
	Low         float64
	Close       float64
	UpdatedAt   pgtype.Timestamptz
}

type GoldNativeSample struct {
	Instrument string
	Bucket     pgtype.Timestamptz
	SampledAt  pgtype.Timestamptz
	SourceAt   pgtype.Timestamptz
	Price      float64
}

type GoldRealtimeSample struct {
	Symbol    string
	Bucket    pgtype.Timestamptz
	SampledAt pgtype.Timestamptz
	SourceAt  pgtype.Timestamptz
	PriceCny  float64
}

type User struct {
	ID          int64
	Openid      string
	Nickname    string
	AvatarUrl   pgtype.Text
	RealName    pgtype.Text
	PhoneNumber pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
