// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package marketsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAppleNotification struct {
	ID          string
	Subject     string
	EventType   string
	IssuedAt    pgtype.Timestamptz
	EventTime   int64
	ProcessedAt pgtype.Timestamptz
}

type AuthChallenge struct {
	ID        string
	NonceHash string
	ExpiresAt pgtype.Timestamptz
}

type AuthCode struct {
	Key       string
	Hash      string
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
	Active    bool
}

type AuthIdentity struct {
	UserID               int64
	Provider             string
	Subject              string
	PasswordHash         string
	AppleRefresh         []byte
	AppleAuthenticatedAt pgtype.Timestamptz
}

type AuthQuota struct {
	Key       string
	Count     int32
	ExpiresAt pgtype.Timestamptz
}

type AuthRefreshHistory struct {
	RefreshHash string
	UserID      int64
	FamilyID    string
	ExpiresAt   pgtype.Timestamptz
}

type AuthSession struct {
	ID              string
	UserID          int64
	Provider        string
	FamilyID        string
	RefreshHash     string
	AuthenticatedAt pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type GoldDailyBar struct {
	Symbol      string
	TradingDate pgtype.Date
	Open        float64
	High        float64
	Low         float64
	Close       float64
	UpdatedAt   pgtype.Timestamptz
}

type GoldNativeSample struct {
	Instrument string
	Bucket     pgtype.Timestamptz
	SampledAt  pgtype.Timestamptz
	SourceAt   pgtype.Timestamptz
	Price      float64
}

type GoldRealtimeSample struct {
	Symbol    string
	Bucket    pgtype.Timestamptz
	SampledAt pgtype.Timestamptz
	SourceAt  pgtype.Timestamptz
	PriceCny  float64
}

type User struct {
	ID          int64
	Openid      string
	Nickname    string
	AvatarUrl   pgtype.Text
	RealName    pgtype.Text
	PhoneNumber pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
